[[repos]]
repo = "builtin"
hooks = [
  {id = "check-added-large-files", args = ["--maxkb=50", "--enforce-all"], exclude = '^uv\.lock$'},
  {id = "check-case-conflict"}, {id = "check-illegal-windows-names"}, {id = "check-merge-conflict"},
  {id = "check-toml"}, {id = "check-yaml"}, {id = "end-of-file-fixer"}, {id = "trailing-whitespace"}
]

[[repos]]
repo = "https://github.com/abravalheri/validate-pyproject"
rev = "0.26"
hooks = [{id = "validate-pyproject"}]

[[repos]]
repo = "https://github.com/betterleaks/betterleaks"
rev = "v1.8.1"
hooks = [{id = "betterleaks"}]

[[repos]]
repo = "https://github.com/sphinx-contrib/sphinx-lint"
rev = "v1.0.2"
hooks = [{id = "sphinx-lint"}]

[[repos]]
repo = "https://github.com/jonathandung/check-empty"
rev = "v1.1.3"
hooks = [{id = "check-empty", files = '^mvlogics/py\.typed$'}]
