from _collections_abc import Generator, Sequence
from decimal import Decimal
from fractions import Fraction
from typing import Self, final, overload
class MemberlessLogicBase:
    @classmethod
    def from_normalized(cls, val: Fraction) -> Self: '''Construct a member of the class from a normalized value, that is, an instance of `fractions.Fraction` between 0 and 1, or report an error if impossible.'''
    @classmethod
    def from_logic_member(cls, member: MemberlessLogicBase) -> Self: '''Convert a member of any logic class to a member of the current class, or report an error if impossible.'''
    def normalized(self) -> Fraction: '''Return the normalized value of the member, that is, a `fractions.Fraction` between 0 and 1 representing its degree of truth.'''
    def convert_to[L: MemberlessLogicBase](self, cls: type[L]) -> L: '''Convert the member to a member of the specified logic class, or report an error if impossible.'''
    def __and__(self, other: Self, /) -> Self: ...
    def __or__(self, other: Self, /) -> Self: ...
    def __invert__(self) -> Self: ...
    def __pos__(self) -> Self: ...
    def __neg__(self) -> Self: ...
    def __xor__(self, other: Self, /) -> Self: ...
    def implies(self, other: Self, /) -> Self: ...
    def iff(self, other: Self, /) -> Self: ...
    def nor(self, other: Self, /) -> Self: ...
    def nand(self, other: Self, /) -> Self: ...
    def xnor(self, other: Self, /) -> Self: ...
    def abjunction(self, other: Self, /) -> Self: ...
    def converse_implies(self, other: Self, /) -> Self: ...
    def converse_abjunction(self, other: Self, /) -> Self: ...
class AbstractLogicBase[R](MemberlessLogicBase):
    @property
    def value(self) -> R: ...
    def __new__(cls, v: R, /) -> Self: ...
class LogicBase[V](AbstractLogicBase[V]):
    @final
    class MemberContainer[R]:
        @property
        def names(self) -> tuple[str, ...]: ...
        def __init__(self, values: dict[str, R]): ...
        def generate(self, value: R) -> LogicBase[R]: ...
        def from_name(self, name: str) -> LogicBase[R]: ...
        def value_from_name(self, name: str, /) -> R: ...
        def name_from_value(self, value: R, /) -> str: ...
        def member_values(self) -> Generator[R]: ...
        def __set_name__(self, owner: type, name: str, /) -> None: ...
        def __iter__(self) -> Generator[LogicBase[R]]: ...
    members: MemberContainer[V]
class InfiniteLogicBase[R](AbstractLogicBase[R]):
    T: Self
    F: Self
    verum: Self
    falsum: Self
    members: dict[R, Self]
class DecimalLogicBase(InfiniteLogicBase[Decimal]):
    @overload
    def __new__(cls, val: Decimal|float, /) -> Self: ...
    @overload
    def __new__(cls, arg: str, /) -> Self: ...
    @overload
    def __new__(cls, v: tuple[int, Sequence[int], int], /) -> Self: ...
class RationalLogicBase(InfiniteLogicBase[Fraction]):
    @overload
    def __new__(cls, arg: str, /) -> Self: ...
    @overload
    def __new__(cls, val: float|Fraction|Decimal, /) -> Self: ...
    @overload
    def __new__(cls, num: int, dem: int, /) -> Self: ...
class StrictLogicBase[R](LogicBase[R]):
    def gullibility(self, other: Self, /) -> Self: ...
    def consensus(self, other: Self, /) -> Self: ...
class GödelLogic(LogicBase[Fraction]): ...
class ŁukasiewiczLogic(LogicBase[Fraction]):
    def strong_disjunction(self, other: Self, /) -> Self: ...
    def strong_conjunction(self, other: Self, /) -> Self: ...
    def diamond(self) -> Self: ...
    def box(self) -> Self: ...
    def doubtful(self) -> Self: ...
class PostLogic(LogicBase[Fraction]): ...
class TNormLogic(DecimalLogicBase):
    def strong_conjunction(self, other: Self, /) -> Self: ...
class RationalTNormLogic(RationalLogicBase):
    def strong_conjunction(self, other: Self, /) -> Self: ...