from _collections_abc import Generator, Sequence
from decimal import Decimal
from fractions import Fraction
from typing import ClassVar, Final, Self, final, overload
class MemberlessLogicBase:
    @classmethod
    def from_normalized(cls, val: Fraction) -> Self: ...
    @classmethod
    def from_logic_member(cls, member: MemberlessLogicBase) -> Self: ...
    def __and__(self, other: Self, /) -> Self: ...
    def __or__(self, other: Self, /) -> Self: ...
    def __invert__(self) -> Self: ...
    def __pos__(self) -> Self: ...
    def __neg__(self) -> Self: ...
    def __xor__(self, other: Self, /) -> Self: ...
    def implies(self, other: Self, /) -> Self: ...
    def iff(self, other: Self, /) -> Self: ...
    def nor(self, other: Self, /) -> Self: ...
    def nand(self, other: Self, /) -> Self: ...
    def xnor(self, other: Self, /) -> Self: ...
    def abjunction(self, other: Self, /) -> Self: ...
    def converse_implies(self, other: Self, /) -> Self: ...
    def converse_abjunction(self, other: Self, /) -> Self: ...
    def normalized(self) -> Fraction: ...
    def convert_to[L: MemberlessLogicBase](self, cls: type[L]) -> L: ...
class AbstractLogicBase[R](MemberlessLogicBase):
    @property
    def value(self) -> R: ...
    def __new__(cls, v: R, /) -> Self: ...
class LogicBase[R](AbstractLogicBase[R]):
    @final
    class MemberContainer[V: LogicBase]:
        @property
        def names(self) -> tuple[str, ...]: '''Is not a property at runtime.'''
        def __init__(self, values: dict[str, R]): ...
        def generate(self, value: R) -> V: ...
        def from_name(self, name: str) -> V: ...
        def value_from_name(self, name: str, /) -> R: ...
        def name_from_value(self, value: R, /) -> str: ...
        def member_values(self) -> Generator[R]: ...
        def __set_name__(self, owner: type, name: str, /) -> None: ...
        def __iter__(self) -> Generator[V]: ...
    members: Final[MemberContainer[Self]]
class InfiniteLogicBase[R](AbstractLogicBase[R]):
    T: ClassVar[Self]
    F: ClassVar[Self]
    verum: ClassVar[Self]
    falsum: ClassVar[Self]
    members: Final[dict[R, Self]]
class DecimalLogicBase(InfiniteLogicBase[Decimal]):
    @overload
    def __new__(cls, val: Decimal|float, /) -> Self: ...
    @overload
    def __new__(cls, arg: str, /) -> Self: ...
    @overload
    def __new__(cls, v: tuple[int, Sequence[int], int], /) -> Self: ...
class RationalLogicBase(InfiniteLogicBase[Fraction]):
    @overload
    def __new__(cls, arg: str, /) -> Self: ...
    @overload
    def __new__(cls, val: float|Fraction|Decimal, /) -> Self: ...
    @overload
    def __new__(cls, num: int, dem: int, /) -> Self: ...
class StrictLogicBase[R](LogicBase[R]):
    def gullibility(self, other: Self, /) -> Self: ...
    def consensus(self, other: Self, /) -> Self: ...
class GödelLogic(LogicBase[Fraction]): ...
class ŁukasiewiczLogic(LogicBase[Fraction]):
    def strong_disjunction(self, other: Self, /) -> Self: ...
    def strong_conjunction(self, other: Self, /) -> Self: ...
    def diamond(self) -> Self: ...
    def box(self) -> Self: ...
    def doubtful(self) -> Self: ...
class PostLogic(LogicBase[Fraction]): ...
class TNormLogic(DecimalLogicBase):
    def strong_conjunction(self, other: Self, /) -> Self: ...
class RationalTNormLogic(RationalLogicBase):
    def strong_conjunction(self, other: Self, /) -> Self: ...