name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        persist-credentials: false
        ref: ${{github.event.pull_request.head.sha || github.sha}}
    - uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d
      with:
        enable-cache: false
    - run: uvx ruff check --output-format github
    - run: uvx ty check --output-format github
    - run: uv audit --preview-features audit-command
    - uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054
    - run: uv build
