name: Upload Python Package
on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  release-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/mvlogics/${{github.event.release.name}}
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          python-version: 3.14
          cache-python: true
          activate-environment: true
      - name: Upload to PyPI
        run: uv pip install -e . && uv build && uv publish --token ${{secrets.PYPI_TOKEN}}