name: Python package
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.12, 3.13, 3.14]
    steps:
    - uses: actions/checkout@v6.0.2
    - uses: actions/setup-python@v6.2.0
      with:
        python-version: ${{matrix.python-version}}
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -e .[dev]
        pip check
    - name: Lint with ruff
      run: ruff check . --output-format=github
    - name: Run mypy
      run: python -m mypy mvlogics